# Primary Categories Configuration
# Version: v4
# These are mutually exclusive - each recipe gets exactly one primary category

categories:
  Not a Recipe:
    description: "Items that were saved by mistake and are completely unrelated to food/cooking"
    criteria:
      - "Content completely unrelated to food, cooking, or kitchen"
      - "Random bookmarks or mistakenly saved non-culinary content"
      - "Books, articles, or websites about non-food topics"
    examples: ["Random Wikipedia Articles", "Non-Food Books", "Unrelated Links"]
    precedence: 0  # Highest precedence - if it's completely unrelated, categorize as such
    
  Breakfast:
    description: "Foods primarily intended for breakfast consumption"
    criteria:
      - "Traditional breakfast items (pancakes, waffles, oatmeal, cereal)"
      - "Breakfast pastries (muffins, scones, coffee cake)"
      - "Egg dishes for breakfast (scrambled, omelets, frittatas)"
      - "Breakfast meats and sides"
      - "Smoothie ingredient lists and breakfast drink recipes"
    examples: ["Pancakes", "Overnight Oats", "Breakfast Burrito", "Coffee Cake", "Green Smoothie Ingredients"]
    precedence: 1  # High precedence - breakfast items stay in breakfast
    
  Desserts:
    description: "Sweet dishes intended for dessert"
    criteria:
      - "Cakes, pies, and sweet pastries"
      - "Cookies and sweet baked goods"
      - "Ice cream and frozen desserts"
      - "Puddings and sweet treats"
    examples: ["Chocolate Cake", "Apple Pie", "Chocolate Chip Cookies", "Ice Cream"]
    precedence: 2
    
  Baking:
    description: "Bread, rolls, and yeasted/quick bread items (not desserts)"
    criteria:
      - "Bread (sandwich bread, artisan breads, sourdough)"
      - "Rolls and buns (dinner rolls, hamburger buns)"
      - "Biscuits and savory quick breads"
      - "Pizza dough and flatbreads"
    examples: ["Sourdough Bread", "Dinner Rolls", "Focaccia", "Biscuits"]
    precedence: 3
    
  Recipe Components:
    description: "Recipe building blocks and components used in other dishes"
    criteria:
      - "Spice mixes and seasoning blends"
      - "Base sauces and stocks"
      - "Doughs and batters meant for further use"
      - "Marinades and dressings"
      - "Condiments and flavoring agents"
    examples: ["Taco Seasoning Mix", "Basic Tomato Sauce", "Pizza Dough", "Ranch Dressing", "Spice Blend"]
    precedence: 4
    
  Substitutions:
    description: "Ingredient replacements and alternatives for dietary needs or availability"
    criteria:
      - "Dairy-free substitutes (milk, buttermilk, cheese alternatives)"
      - "Egg substitutes and replacements"
      - "Gluten-free flour blends and alternatives"
      - "Sugar substitutes and sweetener alternatives"
      - "Ingredient swaps for allergies or preferences"
    examples: ["Dairy-Free Buttermilk", "Egg Substitute", "Gluten-Free Flour Blend", "Cashew Cream"]
    precedence: 5
    
  Beef:
    description: "Dishes where beef is the primary protein"
    criteria:
      - "Steaks, roasts, and beef cuts as main ingredient"
      - "Ground beef dishes (burgers, meatballs, casseroles)"
      - "Beef stews and braises"
    examples: ["Beef Stew", "Hamburgers", "Pot Roast", "Beef Tacos"]
    precedence: 6
    
  Chicken:
    description: "Dishes where chicken is the primary protein"
    criteria:
      - "Whole chicken or chicken parts as main ingredient"
      - "Chicken breasts, thighs, wings as focus"
      - "Ground chicken dishes"
    examples: ["Roast Chicken", "Chicken Curry", "Buffalo Wings", "Chicken Salad"]
    precedence: 6
    
  Pork:
    description: "Dishes where pork is the primary protein"
    criteria:
      - "Pork chops, tenderloin, roasts"
      - "Ham and bacon as main ingredient (not just flavoring)"
      - "Ground pork dishes"
      - "Sausage-based dishes where sausage is the main component"
    examples: ["Pork Chops", "Ham Dinner", "Pulled Pork", "Sausage Pasta"]
    precedence: 6
    
  Seafood:
    description: "Dishes where fish or shellfish is the primary protein"
    criteria:
      - "Fish fillets, whole fish, or fish steaks as main ingredient"
      - "Shellfish (shrimp, crab, lobster, mussels, etc.)"
      - "Mixed seafood dishes"
    examples: ["Salmon Fillet", "Shrimp Scampi", "Fish Tacos", "Crab Cakes"]
    precedence: 6
    
  Vegetarian:
    description: "Plant-based dishes or dishes where vegetables/grains are the main component"
    criteria:
      - "No meat, poultry, or seafood as main ingredients"
      - "Vegetable-based main dishes"
      - "Grain and legume-based meals"
      - "Pasta dishes without meat"
      - "Ingredient lists for vegetarian dishes (like smoothies, salads)"
    examples: ["Vegetable Stir Fry", "Caprese Salad", "Lentil Curry", "Margherita Pizza", "Smoothie Ingredient Mix"]
    precedence: 6
    
  Sides & Appetizers:
    description: "Dishes intended to accompany main courses or serve as starters"
    criteria:
      - "Side dishes (vegetables, starches, salads)"
      - "Appetizers and hors d'oeuvres"
      - "Dips and spreads"
      - "Small plates and finger foods"
    examples: ["Garlic Bread", "Caesar Salad", "Hummus", "Deviled Eggs"]
    precedence: 7
    
  Cooking Reference:
    description: "Cooking-related articles, tips, techniques, and reference materials"
    criteria:
      - "Cooking articles, tips, and technique explanations"
      - "Equipment reviews and kitchen tool recommendations"
      - "Food history, culture, or educational content about cooking"
      - "Cooking method explanations and tutorials"
      - "Kitchen reference materials and guides"
      - "Food science and culinary education content"
    examples: ["How to Sharpen Knives", "Guide to Cooking Methods", "Equipment Reviews", "Food History Articles"]
    precedence: 8  # Lowest precedence - only wins when clearly not a recipe

# Special Notes:
# - Precedence determines conflict resolution (lower number = higher precedence)
# - "Not a Recipe" has highest precedence for completely unrelated content
# - Recipe categories (1-7) have higher precedence than "Cooking Reference" (8)
# - "Recipe Components" and "Substitutions" are NEW categories for recipe building blocks
# - Ingredient lists and recipe components are treated as recipes, not references
# - "Cooking Reference" only for articles, tips, and educational content (not actual recipes)
