# Usage & Personal Tags Configuration
# Version: v1
# These tags reflect personal usage patterns and preferences

usage_tags:
  Favorite:
    description: "Recipes that are frequently made and loved by the family"
    criteria:
      - "Made regularly (monthly or more often)"
      - "Family favorites that everyone enjoys"
      - "Go-to recipes for specific occasions or needs"
      - "Recipes you would recommend to others"
    assignment: "manual"  # Should be manually assigned, not auto-detected
    priority: "high"
    
  Tried/Tested:
    description: "Recipes that have been made at least once successfully"
    criteria:
      - "Have actually cooked this recipe before"
      - "Know it works and tastes good"
      - "Have practical experience with the recipe"
      - "Can vouch for the quality and instructions"
    assignment: "manual"  # Should be manually assigned, not auto-detected
    priority: "medium"
    

# Usage Guidelines:
# - Manual assignment tags should not be auto-assigned by LLM
# - Auto assignment tags can be suggested by LLM based on content
# - Priority affects how prominently these tags are displayed
# - These tags help with workflow and personal organization
# - Consider usage patterns when organizing recipe views
